# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdda6cbb9d515462fef4c60937b554b2b0581f1d8e08ad6a6e26cb3beed91457631998fbbfe4f0ed85bd73e5fac5ee257826c28a364972bcf5f14d38e3cd2fcd

test:
  secret_key_base: c85934fa7e304c0787909a89db1b1deab00a5661c5bc00c62f1a502903576ff1afa5dc748fd8db936e160a7576fad7d914445fee62e553e88da5fe81b67ec88b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
